---
- name: installing git
  become: yes
  apt:
     name: git
     update_cache: yes

- name: fetching the code
  git:
     repo: https://github.com/JigarProjects/agentsystem.git
     dest: agentSystem

- name: setting run time environment
  become: yes
  apt:
     name: default-jre,default-jdk
